name: gli-docking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - biopython
  - numpy
  - pandas
  - matplotlib
  - scipy
  - rdkit
  - pymol-open-source
  - openbabel
  - pip
  - pip:
    - prody
    - MDAnalysis